version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service/statistic-server
    image: statistic-server
    container_name: statistic-server-container

    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  ewm-service:
#    build: ./ewm-main-service

#  ewm-db:
#    image: postgres:14-alpine
